title: My 1st GitHub blog
author: @tflesui
email: tflesui@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  GitHub blog for Teluluai Francis Lesui aka Frankie Lesui aka tflesui! Note to self: I can edit this
  line in _config.yml. Look to this GitHub account for projects and portfolios as I will continue to work toward my dream of 
  being a developer. (I hope this repo is the first result for
  Google searches on Teluluai "Frankie" Lesui) and in your feed.xml site description. Stay tuned!

# social links
twitter_username: @tflesui
github_username:  @tflesui

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
